spring:
  application:
    name: nbc-w6-newsfeed


  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/academy
    username: root
    password: 1234


---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local

