spring:
  application:
    name: nbc-w6-newsfeed

jpa:
  hibernate:
    ddl-auto: update

jwt:
  secret: "abcdefghijklmnopqrstuvwxyz123456"
  expiration: 3600000

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local

