spring:
  application:
    name: nbc-w6-newsfeed

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/newsfeed
    username: root
    password: 1878
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update